# Generated by Django 6.0.5 on 2026-05-25 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=64)),
                ('serial_number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='infrastructure.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='Planned', max_length=32)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='uniq_active_site_name')],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='infrastructure.site'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('connection_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(db_index=True, default='Disconnected', max_length=32)),
                ('end_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connections_ending_here', to='infrastructure.device')),
                ('start_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connections_starting_here', to='infrastructure.device')),
                ('end_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connections_ending_here', to='infrastructure.interface')),
                ('start_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connections_starting_here', to='infrastructure.interface')),
                ('end_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_ending_here', to='infrastructure.site')),
                ('start_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_starting_here', to='infrastructure.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='uniq_active_device_name'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('serial_number',), name='uniq_active_device_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('connection_id',), name='uniq_active_connection_connection_id'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Connected', 'Disconnected'])), name='connection_status_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['String', 'Active', 'Planned', 'Decommissioned'])), name='site_status_allowed_values'),
        ),
    ]
