# Generated by Django 6.0.5 on 2026-05-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Connected', 'Disconnected'])), name='connection_status_allowed_values'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['String', 'Active', 'Planned', 'Decommissioned'])), name='site_status_allowed_values'),
        ),
    ]
