# Generated by Django 6.0.5 on 2026-05-26 02:17

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_create_admin_superuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={
                "verbose_name": "connection",
                "verbose_name_plural": "connections",
            },
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "device", "verbose_name_plural": "devices"},
        ),
        migrations.AlterModelOptions(
            name="interface",
            options={"verbose_name": "interface", "verbose_name_plural": "interfaces"},
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"verbose_name": "site", "verbose_name_plural": "sites"},
        ),
        migrations.AlterModelManagers(
            name="connection",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="device",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="interface",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="site",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="interface",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("device", "name"),
                name="uniq_active_interface_device_name",
            ),
        ),
    ]
