# Generated by Django 6.0.5 on 2026-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0003_alter_connection_options_alter_device_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="speed",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="throughput in Mbps"
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="status",
            field=models.CharField(db_index=True, default="Up", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="interface",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["Up", "Down", "Maintenance"])),
                name="interface_status_allowed_values",
            ),
        ),
    ]
